export const DEFINE_USERNAME = "DEFINE_USERNAME";
export const HANDLE_LOGIN_VISIBILITY = "HANDLE_LOGIN_VISIBILITY";
export const DEFINE_GAME_SCORE = "DEFINE_GAME_SCORE";
export const GAME_FINISHED = "GAME_FINISHED";
export const DEFINE_CARDS = "DEFINE_CARDS";
export const UPDATE_SCOREBOARD = "UPDATE_SCOREBOARD";
